qlct_nhom/urls.py
from django.urls import path
from .views import show_qlct_nhom_page, yc_them_nhom, them_nhom, yc_them_vi_nhom, them_vi_nhom, yc_them_chi_tieu, them_chi_tieu,  them_nhom_user, yc_them_nhom_user, xoa_nhom_user, lay_ds_hoa_don, lay_ds_user, info_nhom_user


urlpatterns = [
    path('', show_qlct_nhom_page, name='qlct_nhom_page'),
    path('themnhom/', yc_them_nhom, name='themnhom'),
    path('themnhom/thuc_hien', them_nhom, name='thuc_hien_them_nhom'),
    path('them-nhomuser/', yc_them_nhom_user, name='them_nhom_user'),
    path('them-nhomuser/thuc-hien', them_nhom_user, name='thuc_hien_them_nhom_user'),
    path('xoa-nhomuser/thuc-hien', xoa_nhom_user, name='thuc_hien_xoa_nhom_user'),
    path('themvinhom/', yc_them_vi_nhom, name='them_vinhom'),
    path('themvinhom/thuc-hien', them_vi_nhom, name='thuc_hien_them_vinhom'),
    path('ds-user/<int:id_nhom>', lay_ds_user, name='ds_user'),
    path('ds-user/user-info/<int:id_user>', info_nhom_user, name='nhom_user_info'),
    path('themchitieu', yc_them_chi_tieu, name='them_chitieu'),
    path('themchitieu/thuc-hien', them_chi_tieu, name='thuc_hien_them_chi_tieu_nhom'),
]

sono/urls.py
from django.urls import path
from .views import show_sono_page, yc_them_so_no, them_sono, chi_tiet_so_no


urlpatterns = [
    path('', show_sono_page, name='sono_page'),
    path('themsono/', yc_them_so_no, name='them_sono'),
    path('themsono/thuc_hien', them_sono, name='thuc_hien_them_sono'),
    path('chitiet-sono/<int:id_sono>', chi_tiet_so_no, name='chi_tiet_sono'),
]

web_qlct/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('qlct_ca_nhan/', include('qlct_ca_nhan.urls')),
    path('qlct_nhom/', include('qlct_nhom.urls')),
    path('sono/', include('sono.urls')),
    path('tienich/', include('tienich.urls')), 
]

hoadon/models.py
from django.conf import settings
from django.db import models
from qlct_nhom.models import ViNhom
from qlct_ca_nhan.models import LinhVuc, ViCaNhan


# Create your models here.
class HoaDon(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_hoa_don = models.CharField(max_length=45, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    ghi_chu = models.CharField(max_length=500, blank=True, null=True)
    thoi_gian_giao_dich = models.DateTimeField(blank=True, null=True)
    vi_nhom = models.ForeignKey(ViNhom, models.DO_NOTHING, blank=True, null=True)
    linh_vuc = models.ForeignKey(LinhVuc, models.DO_NOTHING)
    vi_ca_nhan = models.ForeignKey(ViCaNhan, models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.ten_hoa_don

    class Meta:
        # managed = False
        db_table = 'hoa_don'

qlct_nhom/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class NhomUser(models.Model):
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING)
    nhom = models.ForeignKey('Nhom', on_delete=models.DO_NOTHING)
    dinh_muc = models.IntegerField(null=True)
    is_leader = models.IntegerField(default=0)

    class Meta:
        # managed = False
        db_table = 'nhom_user'
        unique_together = (('auth_user', 'nhom'),)


class Nhom(models.Model):
    ten = models.CharField(max_length=50, default='Test')
    dinh_muc = models.IntegerField()
    is_deleted = models.IntegerField(default=0)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through=NhomUser)

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'nhom'


class ViNhom(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten = models.CharField(max_length=45, blank=True, null=True)
    dinh_muc = models.IntegerField(blank=True, null=True)
    so_du = models.IntegerField(blank=True, null=True)
    auth_group = models.ForeignKey(Nhom, on_delete=models.CASCADE)

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'vi_nhom'

sono/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


# Create your models here.
class SoNo(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_so_no = models.CharField(max_length=200, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    doi_tac = models.CharField(max_length=200, blank=True, null=True)
    loai = models.IntegerField(blank=True, null=True)
    ngay_vay = models.DateTimeField(blank=True, null=True)
    ngay_tra = models.DateTimeField(blank=True, null=True)
    is_deleted = models.IntegerField(default=0)
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sono')

    def __str__(self):
        return self.ten_so_no

    def is_due_date(self):
        if self.ngay_tra == timezone.now():
            return True
        else:
            return False

    class Meta:
        # managed = False
        db_table = 'so_no'

qlct_nhom/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from hoadon.views import lay_ds_hoa_don, them_hoa_don
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from .models import Nhom, NhomUser, ViNhom



def show_qlct_nhom_page(request):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    ds_hoa_don = lay_ds_hoa_don(id_vi_ca_nhan = 1)
    x = len (ds_hoa_don)
    
    context = {
        'ds_nhom': ds_nhom,
        'ds_vi': ds_vi,
        'email': current_user.email,
        'chitieu': ds_hoa_don[x-1],
    }
    return render(request, 'qlct_nhom/qlct_nhompage.html', context=context)


def yc_them_nhom(request):
    context = {
        'email': request.user.email,
    }
    return render(request, 'qlct_nhom/themnhom.html', context=context)


def them_nhom(request):
    current_user = request.user
    ten = request.POST['ten']
    dinh_muc = request.POST['dinh_muc']
    
    nhom = Nhom(ten=ten, dinh_muc=dinh_muc)
    nhom.save()
    nhom_user = NhomUser(auth_user=current_user, nhom=nhom, is_leader=1)
    nhom_user.save()
    context = {
        'email': request.user.email,
    }

    return render(request, 'qlct_nhom/themnhom_thuchien.html', context=context)

def xoa_nhom(request, id_nhom):
    nhom = Nhom.objects.get(pk=id_nhom)
    nhom.delete()

def yc_them_nhom_user(request):
    context = {
        'email': request.user.email,
    }
    return render(request, 'qlct_nhom/them_nhomuser.html', context=context)

def them_nhom_user(request, id_nhom, id_user, dinh_muc):

    nhom = Nhom.objects.get(pk=id_nhom)
    user = User.objects.get(pk=id_user)
    nhom_user = NhomUser(auth_user=user, nhom=nhom, dinh_muc=dinh_muc)
    nhom_user.save()
    context = {
        'email': request.user.email,
    }
    return render('qlct_nhom/them_nhomuser_thuchien.html', context=context)


def xoa_nhom_user(request, id_nhom, id_user):
    nhom = Nhom.objects.get(pk=id_nhom)
    user = User.objects.get(pk=id_user)
    nhom_user = NhomUser.objects.filter(auth_user=user, nhom=nhom)
    nhom_user.delete()
    context = {
        'email': request.user.email,
    }
    return render('qlct_nhom/xoa_nhomuser_thuchien.html', context=context)


def lay_ds_user(request, id_nhom):
    id_user = NhomUser.objects.filter(nhom_id = id_nhom).values('auth_user_id')
    ds_user = User.objects.filter(id__in = id_user)
    idnhom = "global"
    idnhom = id_nhom
    context = {
        'email': request.user.email,
        'ds_user': ds_user,
    }   
    return render(request, "qlct_nhom/ds_nhomuser.html", context=context)

def info_nhom_user(request, id_user):
    user = User.objects.get(pk = id_user)
    user_dm = NhomUser.objects.filter(auth_user_id = id_user).values('dinh_muc')
    context = {
        'username': user.username,
        'email': user.email,
        'dinh_muc': user_dm,
    }
    return render(request, 'qlct_nhom/info_nhomuser.html', context=context)

def dat_dinh_muc_user(request, id_nhom, id_user, dinh_muc):
    nhom = Nhom.objects.get(pk=id_nhom)
    if request.user.is_authenticated():
        current_user = request.user
        thanh_vien = NhomUser.objects.filter(auth_user=current_user, nhom=nhom)
        if thanh_vien.is_leader == 1:
            user = User.objects.get(pk=id_user)
            nhom_user = NhomUser.objects.filter(auth_user=user, nhom=nhom)
            nhom_user.dinh_muc = dinh_muc
            nhom_user.save()
            return HttpResponse("thành công")
        else:
            return HttpResponse("Hãy liên lạc chủ nhóm")
    else:
        return HttpResponse("Hãy tạo tài khoản")

def them_vi(request, id_nhom, ten, dinh_muc, so_du):
    nhom = Nhom.objects.get(pk=id_nhom)
    nhom.vinhom_set.create(ten=ten, dinh_muc=dinh_muc, so_du=so_du)


def chinh_sua_vi(request, id_vi, ten, dinh_muc, so_du):
    vi = ViNhom.objects.get(pk=id_vi)
    vi.ten = ten
    vi.dinh_muc = dinh_muc
    vi.so_du = so_du
    vi.save()

def lay_ds_vi(request, id_nhom):
    nhom = Nhom.objects.get(pk=id_nhom)
    ds_vi = nhom.vinhom_set.filter(is_deleted=0)
    return HttpResponse("chức năng lấy ds ví")

def yc_them_vi_nhom(request):
    current_user = request.user
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    context = {
        'ds_nhom': ds_nhom,
    }
    return render(request, 'qlct_nhom/themvinhom.html', context=context)


def them_vi_nhom(request):   
    ten = request.POST['ten']
    dinh_muc = request.POST['dinh_muc']
    so_du = request.POST['so_du']
    id_nhom = request.POST["auth_group"]

    nhom = Nhom.objects.get(pk=id_nhom)
    nhom.vinhom_set.create(ten=ten, dinh_muc=dinh_muc, so_du=so_du)

    return render(request, 'qlct_nhom/themvinhom_thuchien.html')


def yc_them_chi_tieu(request):
    current_user = request.user
    ds_linhvuc = current_user.linhvuc_set.all()
    ds_vi = []
    ds_nhom = current_user.nhom_set.filter(is_deleted=0)
    for nhom in ds_nhom:
        ds_vi_nhom = nhom.vinhom_set.all()
        ds_vi.extend(ds_vi_nhom)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
        'ds_linhvuc': ds_linhvuc,
    }
    return render(request, 'qlct_nhom/themchitieu.html', context)


def them_chi_tieu(request):
    current_user = request.user
    ten_hoa_don = request.POST["ten_hoa_don"]
    so_tien = request.POST["so_tien"]
    ghi_chu = request.POST["ghi_chu"]
    date = request.POST["thoi_gian_giao_dich_0"]
    time = request.POST["thoi_gian_giao_dich_1"]
    id_linhvuc = request.POST["linh_vuc"]
    id_vi = request.POST["vi_nhom"]

    print(ghi_chu)

    if not current_user.is_authenticated:
        print('permission deni')
        return redirect('login')

    date_time = date + ' ' + time
    result = them_hoa_don(
        current_user=current_user,
        ten_hoa_don=ten_hoa_don,
        so_tien=so_tien,
        thoi_gian_giao_dich=date_time,
        id_linh_vuc=id_linhvuc,
        ghichu=ghi_chu,
        id_vi_nhom=id_vi,
    )

    return render(request, 'qlct_nhom/themchitieu_thuchien.html')





qlct_nhom/templates/qlct_nhom/ds_chitieunhom.html
{% extends  "qlct_nhom/qlct_nhom.html" %} 
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        </h4 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxmedium w3-text-teal"></i>LỊCH SỬ CHI TIÊU NHÓM</h4>
        <div class="w3-container">

                <div class="form-row field-ten_hoa_don">
                        <div>
                            <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                <h6>
                                    {{ten_hoa_don}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-linh-vuc">
                        <div>
                            <label for="id_linh_vuc">Lĩnh vực:</label>
                                <h6>
                                    {{linh_vuc}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-so_tien">
                        <div>
                                <label for="id_so_tien">Số tiền:</label>
                                <h6>
                                    {{so_tien}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ghi-chu">
                        <div>
                                <label for="id_ghi_chu">Ghi chú:</label>
                                <h6>
                                    {{ghi_chu}}
                                </h6>
                        </div>
                </div>
        </div>
</div>
    
     {% endblock %} 

qlct_nhom/templates/qlct_nhom/info_nhomuser.html
{% extends  "qlct_nhom/qlct_nhom.html" %} 
{% block content %}

<div class="w3-container w3-card w3-white w3-margin-bottom">
        <h4 class="w3-text-grey w3-padding-16"><i class="fa fa-address-book fa-fw w3-margin-right w3-xxmedium w3-text-teal"></i>THÔNG TIN THÀNH VIÊN:</h4>
        {% comment %} thêm id để xoá khỏi nhóm {% endcomment %}
        <ul class="object-tools">
            <li>   
                <a href="{% url 'thuc_hien_xoa_nhom_user' %}" onclick="return confirmAction()" style="margin-top:-10px">Xoá khỏi nhóm <i class="fa fa-remove"></i></a>
            </li>
        </ul>
        <div class="w3-container">

                <div class="form-row field-ten_user">
                        <div>
                            <label for="id_ten_user">Tên thành viên:</label>
                                <h6>
                                    {{username}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-email">
                        <div>
                            <label for="id_email">Email:</label>
                                <h6>
                                    {{email}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-dinh_muc">
                        <div>
                                <label for="id_dinh_muc">Định mức:</label>
                                <h6>
                                    {{dinh_muc}}
                                </h6>
                        </div>
                </div>
        </div>
</div>
    
     {% endblock %} 

qlct_nhom/templates/qlct_nhom/qlct_nhompage.html
{% extends  "qlct_nhom/qlct_nhom.html" %} 
{% block content %}

<div class="w3-container w3-card w3-white w3-margin-bottom">
        <h4 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxmedium w3-text-teal"></i>CHI TIÊU CÁ NHÂN GẦN ĐÂY:</h4>
        <div class="w3-container">

                <div class="form-row field-ten_hoa_don">
                        <div>
                            <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                <h6>
                                    {{chitieu.ten_hoa_don}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-linh-vuc">
                        <div>
                            <label for="id_linh_vuc">Lĩnh vực:</label>
                                <h6>
                                    {{chitieu.linh_vuc}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-so_tien">
                        <div>
                                <label for="id_so_tien">Số tiền:</label>
                                <h6>
                                    {{chitieu.so_tien}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ghi-chu">
                        <div>
                                <label for="id_ghi_chu">Ghi chú:</label>
                                <h6>
                                    {{chitieu.ghi_chu}}
                                </h6>
                        </div>
                </div>
        </div>
</div>
    
     {% endblock %} 

qlct_nhom/templates/qlct_nhom/them_nhomuser.html
{% extends  "qlct_nhom/qlct_nhom.html" %}
{% block content %}

<!-- form thêm user vào nhóm, có khi không cần -->
<form action="-thuc_hien_them_nhom_user" method="post" id="nhomuser_form" novalidate>
    <div>
        <fieldset class="module aligned ">
            <div class="form-row field-nhom">
                <div>
                    <label class="required" for="id_nhom">Nhóm:</label>
                    <div class="related-widget-wrapper">
                        <select name="nhom" required id="id_nhom">
                            <option value="" selected>---------</option>
                            {% for nhom in ds_nhom %}
                            <option class="w3-bar-item w3-button w3-center">{{ nhom.ten }}</option> 
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-row field-user">
                <div>
                    <label class="required" for="id_user">User:</label>
                    <div class="related-widget-wrapper">
                        <select name="user" required id="id_user">
                            <option value="" selected>---------</option>
                            {% for user in ds_user %}
                            <option class="w3-bar-item w3-button w3-center">{{ user.ten }}</option> 
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-row field-dinh_muc">
                <div>
                    <label class="required" for="id_dinh_muc">Định mức:</label>
                    <input type="number" name="dinh_muc" class="vIntegerField" required id="id_dinh_muc">
                </div>
            </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="Save" class="default" name="_save">
        </div>
        <script type="text/javascript" id="django-admin-form-add-constants" src="/static/admin/js/change_form.js"
            data-model-name="nhomuser">
            </script>
        <script type="text/javascript" id="django-admin-prepopulated-fields-constants"
            src="/static/admin/js/prepopulate_init.js" data-prepopulated-fields="[]">
            </script>
    </div>
</form>
</div>
<!-- END Content -->
{% endblock %}

qlct_nhom/templates/qlct_nhom/them_nhomuser_thuchien.html
{% extends "qlct_nhom/qlct_nhom.html" %}
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        <div class="w3-container w3-center w3-content" style="margin-top:155px; margin-bottom:150px; color:hsl(201, 18%, 37%);">
        <h1>Thêm thành viên nhóm thành công!</h1>
        </div>            
</div>
{% endblock %}

qlct_nhom/templates/qlct_nhom/themchitieu.html
{% extends  "qlct_nhom/qlct_nhom.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_chi_tieu_nhom' %}" method="post" id="hoadon_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten_hoa_don">
                                <div>
                                        <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                        <input type="text" name="ten_hoa_don" class="vTextField" maxlength="45"
                                                id="id_ten_hoa_don">
                                </div>
                        </div>
                        <div class="form-row field-so_tien">
                                <div>
                                        <label for="id_so_tien">Số tiền:</label>
                                        <input type="number" name="so_tien" class="vIntegerField" id="id_so_tien">
                                </div>
                        </div>
                        <div class="form-row field-ghi-chu">
                                <div>
                                        <label for="id_ghi_chu">Ghi chú:</label>
                                        <input type="text" name="ghi_chu" class="vTextField" maxlength="45"
                                                id="id_ghi_chu">
                                </div>
                        </div>
                        <div class="form-row field-thoi_gian_giao_dich">
                                <div>
                                        <label for="id_thoi_gian_giao_dich_0">Thời gian giao dịch:</label>
                                        <p class="datetime">
                                                Date: <input type="text" name="thoi_gian_giao_dich_0" class="vDateField"
                                                        size="10" id="id_thoi_gian_giao_dich_0">
                                                <br>
                                                Time: <input type="text" name="thoi_gian_giao_dich_1" class="vTimeField"
                                                        size="8" id="id_thoi_gian_giao_dich_1">
                                        </p>
                                </div>
                        </div>
                        <!-- <div class="form-row field-vi_nhom"> -->
                        <!-- <div> -->
                        <!-- <label for="id_vi_nhom">Ví nhóm:</label> -->
                        <!-- <div class="related-widget-wrapper"> -->
                        <!-- <select name="vi_nhom" id="id_vi_nhom"> -->
                        <!-- <option value="" selected>---------</option> -->
                        <!-- thêm vòng for cho ví nhóm vào đây -->
                        <!-- </select> -->
                        <!-- limk thêm ví nhóm -->
                        <!-- <a class="related-widget-wrapper-link add-related" id="add_id_vi_nhom" href=# title="Add another vi nhom"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <div class="form-row field-linh_vuc">
                                <div>
                                        <label class="required" for="id_linh_vuc">Lĩnh vực:</label>
                                        <div class="related-widget-wrapper">
                                                <!-- vòng for thêm lĩnh vực -->
                                                <select name="linh_vuc" required id="id_linh_vuc">
                                                        <option value=-1 selected>---------</option>
                                                        {% for linhvuc in ds_linhvuc %}
                                                                <option value= {{ linhvuc.id }}> {{ linhvuc }} </option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm lĩnh vực -->
                                                <a class="related-widget-wrapper-link add-related" id="add_id_linh_vuc"
                                                        href="{% url 'themlinhvuc' %}" title="Add another linh vuc"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
                        <div class="form-row field-vi-nhom">
                                <div>
                                        <label for="id_vi-nhom">Ví nhóm:</label>
                                        <div class="related-widget-wrapper">
                                                <!--vòng for thêm ví nhóm -->
                                                <select name="vi_nhom" id="id_vi-nhom">
                                                        <option value=-1 selected>---------</option>
                                                        {% for vi in ds_vi %}
                                                        <!-- cần thêm link vào đây (link dến lấy chi tiết ví) -->
                                                        <option value={{vi.id}}>{{ vi.ten }}</option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm ví -->
                                                <a class="related-widget-wrapper-link add-related"
                                                        id="add_id_vi-nhom" href="{% url 'them_vinhom' %}"
                                                        title="Add another vi ca nhan"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
        </div>
        </fieldset>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

qlct_nhom/templates/qlct_nhom/themchitieu_thuchien.html
{% extends "qlct_nhom/qlct_nhom.html" %}
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        <div class="w3-container w3-center w3-content" style="margin-top:155px; margin-bottom:150px; color:hsl(201, 18%, 37%);">
        <h1>Thêm chi tiêu nhóm thành công!</h1>
        </div>            
</div>
{% endblock %}

qlct_nhom/templates/qlct_nhom/themnhom.html
{% extends  "qlct_nhom/qlct_nhom.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_nhom' %}" method="post" id="linhvuc_form" onsubmit="return confirmAction()" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên nhóm</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten">
                                </div>
                        </div>
                        <div class="form-row field-dinh_muc">
                                <div>
                                        <label for="id_dinh_muc">Định mức:</label>
                                        <input type="number" name="dinh_muc" class="vIntegerField" id="id_dinh_muc">
                                </div>
                        </div>
                </fieldset>
        </div>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

qlct_nhom/templates/qlct_nhom/themnhom_thuchien.html
{% extends "qlct_nhom/qlct_nhom.html" %}
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        <div class="w3-container w3-center w3-content" style="margin-top:155px; margin-bottom:150px; color:hsl(201, 18%, 37%);">
        <h1>Thêm nhóm thành công!</h1>
        </div>            
</div>
{% endblock %}

qlct_nhom/templates/qlct_nhom/themvinhom.html
{% extends  "qlct_nhom/qlct_nhom.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_vinhom' %}" method="post" id="vinhom_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên:</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten" value="hieu" >
                                </div>
                        </div>
                        <div class="form-row field-dinh_muc">
                                <div>
                                        <label for="id_dinh_muc">Định mức:</label>
                                        <input type="number" name="dinh_muc" class="vIntegerField" id="id_dinh_muc">
                                </div>
                        </div>
                        <div class="form-row field-so_du">
                                <div>
                                        <label for="id_so_du">Số dư:</label>
                                        <input type="number" name="so_du" class="vIntegerField" id="id_so_du">
                                </div>

                        </div>
                        <div class="form-row field-auth_group">
                                <div>
                                        <label class="required" for="id_auth_group">Auth group:</label>
                                        <div class="related-widget-wrapper">
                                                <select name="auth_group" required id="id_auth_group">
                                                        <option value="" selected>---------</option>
                                                        <!-- cần có biến ds_nhom ở context -->
                                                        {% for nhom in ds_nhom %} 
                                                                <option value= {{ nhom.id }}> {{ nhom }} </option>
                                                        {% endfor %}
                                                </select>
                                                <a class="related-widget-wrapper-link add-related"
                                                        id="add_id_auth_group" href="{% url 'themnhom' %}" title="Add another nhom"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
                </fieldset>
                <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="_save">
                </div>
        </div>
</form>
</div>


{% endblock %}