qlct_ca_nhan/urls.py
from django.urls import path
from .views import them_vi, yc_them_vi, show_qlct_ca_nhan_page, yc_them_linhvuc, them_linhvuc, yc_them_chi_tieu, them_chitieu, lay_ls_chi_tieu, lay_bieu_do


urlpatterns = [
    path('', show_qlct_ca_nhan_page, name='qlct_canhan_page'),
    path('themvi', yc_them_vi, name='themvi'),
    path('themvi/thuc_hien', them_vi, name='thuc_hien_them_vi'),
    path('themlinhvuc', yc_them_linhvuc, name='themlinhvuc'),
    path('themlinhvuc/thuc_hien', them_linhvuc, name='thuc_hien_them_linh_vuc'),
    path('lsct/<int:id_vi>', lay_ls_chi_tieu, name = 'lay_ls_chi_tieu' ),
    path('bieudo/<int:id_vi>', lay_bieu_do, name = 'lay_bieu_do'),
    path('themchitieu/', yc_them_chi_tieu, name='themchitieu'),
    path('themchitieu/thuc_hien', them_chitieu, name='thuc_hien_them_chi_tieu'),
]

sono/urls.py
from django.urls import path
from .views import show_sono_page, yc_them_so_no, them_sono, chi_tiet_so_no


urlpatterns = [
    path('', show_sono_page, name='sono_page'),
    path('themsono/', yc_them_so_no, name='them_sono'),
    path('themsono/thuc_hien', them_sono, name='thuc_hien_them_sono'),
    path('chitiet-sono/<int:id_sono>', chi_tiet_so_no, name='chi_tiet_sono'),
]

web_qlct/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('qlct_ca_nhan/', include('qlct_ca_nhan.urls')),
    path('qlct_nhom/', include('qlct_nhom.urls')),
    path('sono/', include('sono.urls')),
    path('tienich/', include('tienich.urls')), 
]

hoadon/models.py
from django.conf import settings
from django.db import models
from qlct_nhom.models import ViNhom
from qlct_ca_nhan.models import LinhVuc, ViCaNhan


# Create your models here.
class HoaDon(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_hoa_don = models.CharField(max_length=45, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    ghi_chu = models.CharField(max_length=500, blank=True, null=True)
    thoi_gian_giao_dich = models.DateTimeField(blank=True, null=True)
    vi_nhom = models.ForeignKey(ViNhom, models.DO_NOTHING, blank=True, null=True)
    linh_vuc = models.ForeignKey(LinhVuc, models.DO_NOTHING)
    vi_ca_nhan = models.ForeignKey(ViCaNhan, models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.ten_hoa_don

    class Meta:
        # managed = False
        db_table = 'hoa_don'

qlct_ca_nhan/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class ViCaNhan(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten = models.CharField(max_length=45, blank=True, null=True)
    dinh_muc = models.IntegerField(blank=True, null=True)
    so_du = models.IntegerField(blank=True, null=True)
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_deleted = models.IntegerField(default=0)
    # 0 - chưa xóa, 1 - đã xóa

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'vi_ca_nhan'


class LinhVuc(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten = models.CharField(max_length=45, blank=True, null=True)
    loai = models.IntegerField(blank=True, null=True) # 1 là tiêu 0 là thu
    linh_vuc = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True)
    auth_user = models.ManyToManyField(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.ten

    class Meta:
        # managed = False
        db_table = 'linh_vuc'


# class AuthUserHasLinhVuc(models.Model):
#     auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING, primary_key=True)
#     linh_vuc = models.ForeignKey('LinhVuc', models.DO_NOTHING)
#
#     class Meta:
#         # managed = False
#         db_table = 'auth_user_has_linh_vuc'
#         unique_together = (('auth_user', 'linh_vuc'),)

sono/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


# Create your models here.
class SoNo(models.Model):
    # id = models.IntegerField(primary_key=True)
    ten_so_no = models.CharField(max_length=200, blank=True, null=True)
    so_tien = models.IntegerField(blank=True, null=True)
    doi_tac = models.CharField(max_length=200, blank=True, null=True)
    loai = models.IntegerField(blank=True, null=True)
    ngay_vay = models.DateTimeField(blank=True, null=True)
    ngay_tra = models.DateTimeField(blank=True, null=True)
    is_deleted = models.IntegerField(default=0)
    auth_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sono')

    def __str__(self):
        return self.ten_so_no

    def is_due_date(self):
        if self.ngay_tra == timezone.now():
            return True
        else:
            return False

    class Meta:
        # managed = False
        db_table = 'so_no'

qlct_ca_nhan/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import LinhVuc
from hoadon.views import lay_ds_hoa_don, them_hoa_don


def show_qlct_ca_nhan_page(request, id_vi=1):
    current_user = request.user
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    ds_hoa_don = lay_ds_hoa_don(id_vi_ca_nhan = id_vi)
    x = len (ds_hoa_don)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
        'chitieu': ds_hoa_don[x-1],
    }
    return render(request, 'qlct_ca_nhan/qlct_canhanpage.html', context=context)


def yc_them_vi(request):
    context = {
        'email': request.user.email,
    }
    return render(request, 'qlct_ca_nhan/themvi.html', context=context)


def them_vi(request):
    current_user = request.user
    ten = request.POST['ten']
    dinh_muc = request.POST['dinh_muc']
    sodu = request.POST['so_du']
    if current_user.is_authenticated:
        current_user.vicanhan_set.create(
            ten=ten, dinh_muc=dinh_muc, so_du=sodu, is_deleted=0)
        context = {
        'email': request.user.email,
    }
        return render(request, 'qlct_ca_nhan/themvi_thuchien.html', context=context)
    else:
        print('user invalid')
        return redirect('login')

def lay_ds_vi(request):
    # current_user = authenticate(username='manhieu', password='1234')
    if request.user.is_authenticated():
        current_user = request.user
        ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
        return HttpResponse("chức năng lấy ds ví")
    else:
        return HttpResponse('Bạn cần đăng nhập!')

def chinh_sua_vi(request, ten, dinhmuc, sodu, id):
    vi_ca_nhan = ViCaNhan.objects.get(pk=id)
    vi_ca_nhan.ten = ten
    vi_ca_nhan.dinh_muc = dinhmuc
    vi_ca_nhan.so_du = sodu
    vi_ca_nhan.save()
    return HttpResponse("chỉnh sửa thông tin ví")

def xoa_vi(request, id):
    vi_ca_nhan = ViCaNhan.objects.get(pk=id)
    vi_ca_nhan.is_deleted = 1
    vi_ca_nhan.save()
    return HttpResponse("xóa ví")

def yc_them_linhvuc(request):
    current_user = request.user
    ds_linhvuc = current_user.linhvuc_set.all()
    context = {
        'email': current_user.email,
        'ds_linhvuc': ds_linhvuc
    }
    return render(request, 'qlct_ca_nhan/themlinhvuc.html', context=context)

def them_linhvuc(request):
    current_user = request.user
    ten = request.POST['ten']
    loai = request.POST['loai']
    id_linhvuc_cha = request.POST['linh_vuc']
    # print(id_linhvuc_cha)

    linh_vuc_cha = None

    if current_user.is_authenticated:
        linhvuc = current_user.linhvuc_set.create(ten=ten, loai=loai)
        if int(id_linhvuc_cha) != -1:
            linh_vuc_cha = LinhVuc.objects.get(pk=id_linhvuc_cha)
            linhvuc.linh_vuc = linh_vuc_cha
            linhvuc.save()
        context = {
        'email': request.user.email,
    }
        return render(request, 'qlct_ca_nhan/themlinhvuc.html', context=context)
    else:
        print('user invalid')
        return redirect('login')

def lay_ds_linh_vuc(request):
    # current_user = authenticate(username='manhieu', password='1234')
    if request.user.is_authenticated():
        current_user = request.user
        ds_linh_vuc = current_user.linhvuc_set.all()
        return HttpResponse("lấy ds lĩnh vực của user")
    else:
        return HttpResponse('Bạn cần đăng nhập!')
        
def lay_ls_chi_tieu(request, id_vi):
    ds_hoa_don = lay_ds_hoa_don(id_vi_ca_nhan = id_vi)
    context = {
        'ds_chitieu': ds_hoa_don,
    } 
    return render(request, 'qlct_ca_nhan/lsct.html', context)

def yc_them_chi_tieu(request):
    current_user = request.user
    ds_linhvuc = current_user.linhvuc_set.all()
    ds_vi = current_user.vicanhan_set.filter(is_deleted=0)
    context = {
        'ds_vi': ds_vi,
        'email': current_user.email,
        'ds_linhvuc': ds_linhvuc,
    }
    return render(request, 'qlct_ca_nhan/themchitieu.html', context)


def them_chitieu(request):
    current_user = request.user
    ten_hoa_don = request.POST["ten_hoa_don"]
    so_tien = request.POST["so_tien"]
    ghi_chu = request.POST["ghi_chu"]
    date = request.POST["thoi_gian_giao_dich_0"]
    time = request.POST["thoi_gian_giao_dich_1"]
    id_linhvuc = request.POST["linh_vuc"]
    id_vi = request.POST["vi_ca_nhan"]

    print(ghi_chu)

    if not current_user.is_authenticated:
        print('permission deni')
        return redirect('login')

    date_time = date + ' ' + time
    result = them_hoa_don(
        current_user=current_user,
        ten_hoa_don=ten_hoa_don,
        so_tien=so_tien,
        thoi_gian_giao_dich=date_time,
        id_linh_vuc=id_linhvuc,
        ghichu=ghi_chu,
        id_vi_ca_nhan=id_vi,
    )
    context = {
        'email': request.user.email,
    }
    return render(request, 'qlct_ca_nhan/themchitieu_thuchien.html', context=context)

from django.db.models import Sum
from hoadon.models import HoaDon
def lay_bieu_do(request, id_vi):
    ds_hoa_don = lay_ds_hoa_don(id_vi_ca_nhan = id_vi)
    ds_linh_vuc = HoaDon.objects.values('linh_vuc__ten').annotate(Sum('so_tien'))

    lv1 = ds_linh_vuc[0]['linh_vuc__ten']
    so1= ds_linh_vuc[0]['so_tien__sum']

    lv2 = ds_linh_vuc[1]['linh_vuc__ten']
    so2= ds_linh_vuc[1]['so_tien__sum']

    lv3 = ds_linh_vuc[2]['linh_vuc__ten']
    so3= ds_linh_vuc[2]['so_tien__sum']

    lv4 = ds_linh_vuc[3]['linh_vuc__ten']
    so4= ds_linh_vuc[3]['so_tien__sum']

    lv5 = ds_linh_vuc[4]['linh_vuc__ten']
    so5= ds_linh_vuc[4]['so_tien__sum']

    lv6 = ds_linh_vuc[5]['linh_vuc__ten']
    so6= ds_linh_vuc[5]['so_tien__sum']

    lv7 = ds_linh_vuc[6]['linh_vuc__ten']
    so7= ds_linh_vuc[6]['so_tien__sum']

    lv8 = ds_linh_vuc[7]['linh_vuc__ten']
    so8= ds_linh_vuc[7]['so_tien__sum']

    lv9 = ds_linh_vuc[8]['linh_vuc__ten']
    so9= ds_linh_vuc[8]['so_tien__sum']

    lv10 = ds_linh_vuc[9]['linh_vuc__ten']
    so10= ds_linh_vuc[9]['so_tien__sum']


    context = {
        'lv1': lv1,
        'lv2': lv2,
        'lv3': lv3,
        'lv4': lv4,
        'lv5': lv5,
        'lv6': lv6,
        'lv7': lv7,
        'lv8': lv9,
        'lv9': lv9,
        'lv10': lv10,

        'so1': so1,
        'so2': so2,
        'so3': so3,
        'so4': so4,
        'so5': so5,
        'so6': so6,
        'so7': so7,
        'so8': so8,
        'so9': so9,
        'so10': so10,
        
    }

    print(ds_linh_vuc)
    return render(request, 'qlct_ca_nhan/bieudotron.html', context)

qlct_ca_nhan/templates/qlct_ca_nhan/bieudocot.html
{% extends "users/base11.html" %}
{% block content %}

<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
      var data = google.visualization.arrayToDataTable([
        ['Genre', 'Du Lịch', 'Điện Nước', 'Sinh Hoạt', 'Thể Thao',
         'Phát Sinh', 'Học tập', { role: 'annotation' } ],
        ['Tháng 1', 10, 24, 20, 32, 18, 5, ''],
        ['Tháng 2', 16, 22, 23, 30, 16, 9, ''],
        ['Tháng 3', 28, 19, 29, 30, 12, 13, '']
      ]);

      var options = {
        width: 600,
        height: 400,
        legend: { position: 'top', maxLines: 3 },
        bar: { groupWidth: '75%' },
        isStacked: true,
      };
      var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
      chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="columnchart_values" style="width: 885px; height: 500px;"></div>
  </body>
</html>

{% endblock %}

qlct_ca_nhan/templates/qlct_ca_nhan/bieudotron.html
{% extends "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      var table = [['Chi Phí', '%'], 
                  ['{{lv1}}', {{so1}}],
                  ['{{lv2}}', {{so2}}],
                  ['{{lv3}}', {{so3}}],
                  ['{{lv4}}', {{so4}}],
                  ['{{lv5}}', {{so5}}],
                  ['{{lv6}}', {{so6}}],
                  ['{{lv7}}', {{so7}}],
                  ['{{lv8}}', {{so8}}],
                  ['{{lv9}}', {{so9}}],
                  ['{{lv10}}', {{so10}}]
                  ];
    


      function drawChart() {
        var data = google.visualization.arrayToDataTable(table);
        var options = {
          title: 'Biểu Đồ Chi Tiêu theo Lĩnh Vực'
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="piechart" style="width: 885px; height: 500px;"></div>
  </body>

</html>

{% endblock %}

qlct_ca_nhan/templates/qlct_ca_nhan/ds_chitieu.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %} 
{% block content %}

<div class="w3-container w3-card w3-white w3-margin-bottom">
        <h4 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxmedium w3-text-teal"></i>LỊCH SỬ CHI TIÊU:</h4>
        <div class="w3-container">

                <div class="form-row field-ten_hoa_don">
                        <div>
                            <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                <h6>
                                    {{ten_hoa_don}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-linh-vuc">
                        <div>
                            <label for="id_linh_vuc">Lĩnh vực:</label>
                                <h6>
                                    {{linh_vuc}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-so_tien">
                        <div>
                                <label for="id_so_tien">Số tiền:</label>
                                <h6>
                                    {{so_tien}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ghi-chu">
                        <div>
                                <label for="id_ghi_chu">Ghi chú:</label>
                                <h6>
                                    {{ghi_chu}}
                                </h6>
                        </div>
                </div>

        </div>
</div>
    
     {% endblock %} 

qlct_ca_nhan/templates/qlct_ca_nhan/qlct_canhanpage.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %} 
{% block content %}

<div class="w3-container w3-card w3-white w3-margin-bottom">
        <h4 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxmedium w3-text-teal"></i>CHI TIÊU CÁ NHÂN GẦN ĐÂY:</h4>
        <div class="w3-container">

                <div class="form-row field-ten_hoa_don">
                        <div>
                            <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                <h6>
                                    {{chitieu.ten_hoa_don}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-linh-vuc">
                        <div>
                            <label for="id_linh_vuc">Lĩnh vực:</label>
                                <h6>
                                    {{chitieu.linh_vuc}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-so_tien">
                        <div>
                                <label for="id_so_tien">Số tiền:</label>
                                <h6>
                                    {{chitieu.so_tien}}
                                </h6>
                        </div>
                </div>

                <div class="form-row field-ghi-chu">
                        <div>
                                <label for="id_ghi_chu">Ghi chú:</label>
                                <h6>
                                    {{chitieu.ghi_chu}}
                                </h6>
                        </div>
                </div>
        </div>
</div>
    
     {% endblock %} 

qlct_ca_nhan/templates/qlct_ca_nhan/themchitieu.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_chi_tieu' %}" method="post" id="hoadon_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten_hoa_don">
                                <div>
                                        <label for="id_ten_hoa_don">Tên hoá đơn:</label>
                                        <input type="text" name="ten_hoa_don" class="vTextField" maxlength="45"
                                                id="id_ten_hoa_don">
                                </div>
                        </div>
                        <div class="form-row field-so_tien">
                                <div>
                                        <label for="id_so_tien">Số tiền:</label>
                                        <input type="number" name="so_tien" class="vIntegerField" id="id_so_tien">
                                </div>
                        </div>
                        <div class="form-row field-ghi-chu">
                                <div>
                                        <label for="id_ghi_chu">Ghi chú:</label>
                                        <input type="text" name="ghi_chu" class="vTextField" maxlength="45"
                                                id="id_ghi_chu">
                                </div>
                        </div>
                        <div class="form-row field-thoi_gian_giao_dich">
                                <div>
                                        <label for="id_thoi_gian_giao_dich_0">Thời gian giao dịch:</label>
                                        <p class="datetime">
                                                Date: <input type="text" name="thoi_gian_giao_dich_0" class="vDateField"
                                                        size="10" id="id_thoi_gian_giao_dich_0">
                                                <br>
                                                Time: <input type="text" name="thoi_gian_giao_dich_1" class="vTimeField"
                                                        size="8" id="id_thoi_gian_giao_dich_1">
                                        </p>
                                </div>
                        </div>
                        <!-- <div class="form-row field-vi_nhom"> -->
                        <!-- <div> -->
                        <!-- <label for="id_vi_nhom">Ví nhóm:</label> -->
                        <!-- <div class="related-widget-wrapper"> -->
                        <!-- <select name="vi_nhom" id="id_vi_nhom"> -->
                        <!-- <option value="" selected>---------</option> -->
                        <!-- thêm vòng for cho ví nhóm vào đây -->
                        <!-- </select> -->
                        <!-- link thêm ví nhóm -->
                        <!-- <a class="related-widget-wrapper-link add-related" id="add_id_vi_nhom" href=# title="Add another vi nhom"><img src="/static/admin/img/icon-addlink.svg" alt="Add"></a> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <!-- </div> -->
                        <div class="form-row field-linh_vuc">
                                <div>
                                        <label class="required" for="id_linh_vuc">Lĩnh vực:</label>
                                        <div class="related-widget-wrapper">
                                                <!-- vòng for thêm lĩnh vực -->
                                                <select name="linh_vuc" required id="id_linh_vuc">
                                                        <option value=-1 selected>---------</option>
                                                        {% for linhvuc in ds_linhvuc %}
                                                                <option value= {{ linhvuc.id }}> {{ linhvuc }} </option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm lĩnh vực -->
                                                <a class="related-widget-wrapper-link add-related" id="add_id_linh_vuc"
                                                        href="{% url 'themlinhvuc' %}" title="Add another linh vuc"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
                        <div class="form-row field-vi_ca_nhan">
                                <div>
                                        <label for="id_vi_ca_nhan">Ví cá nhân:</label>
                                        <div class="related-widget-wrapper">
                                                <!--vòng for thêm ví cá nhân -->
                                                <select name="vi_ca_nhan" id="id_vi_ca_nhan">
                                                        <option value=-1 selected>---------</option>
                                                        {% for vi in ds_vi %}
                                                        <!-- cần thêm link vào đây (link dến lấy chi tiết ví) -->
                                                        <option value={{vi.id}}>{{ vi.ten }}</option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm ví -->
                                                <a class="related-widget-wrapper-link add-related"
                                                        id="add_id_vi_ca_nhan" href="{% url 'themvi' %}"
                                                        title="Add another vi ca nhan"><img
                                                                src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
        </div>
        </fieldset>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

qlct_ca_nhan/templates/qlct_ca_nhan/themchitieu_thuchien.html
{% extends "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        <div class="w3-container w3-center w3-content" style="margin-top:155px; margin-bottom:150px; color:hsl(201, 18%, 37%);">
        <h1>Thêm chi tiêu thành công!</h1>
        </div>            
</div>
{% endblock %}

qlct_ca_nhan/templates/qlct_ca_nhan/themlinhvuc.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_linh_vuc' %}" method="post" id="linhvuc_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên:</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten">
                                </div>
                        </div>
                        <div class="form-row field-loai">
                                <div>
                                        <label for="id_loai">Loại:</label>
                                        <input type="number" name="loai" class="vIntegerField" id="id_loai">
                                </div>
                        </div>
                        <div class="form-row field-linh_vuc">
                                <div>
                                        <label for="id_linh_vuc">Lĩnh vực:</label>
                                        <!-- thêm link lấy ds lĩnh vục hiện có -->
                                        <div class="related-widget-wrapper">
                                                <select name="linh_vuc" id="id_linh_vuc">
                                                        <option value=-1 selected>---------</option>
                                                        {% for linhvuc in ds_linhvuc %}
                                                                <option value= {{ linhvuc.id }}> {{ linhvuc }} </option>
                                                        {% endfor %}
                                                </select>
                                                <!-- link thêm kĩnh vực khác  -->
                                                <a class="related-widget-wrapper-link add-related" id="add_id_linh_vuc"
                                                        href="{% url 'themlinhvuc' %}" title="Add another linh vuc">
                                                        <img src="/static/admin/img/icon-addlink.svg" alt="Add"></a>
                                        </div>
                                </div>
                        </div>
                </fieldset>
                <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="_save">
                </div>
        </div>
</form>
</div>
<!-- END Content -->
{% endblock %}

qlct_ca_nhan/templates/qlct_ca_nhan/themvi.html
{% extends  "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}


<form action="{% url 'thuc_hien_them_vi' %}" method="post" id="linhvuc_form" novalidate>
        {% csrf_token %}
        <div>
                <fieldset class="module aligned ">
                        <div class="form-row field-ten">
                                <div>
                                        <label for="id_ten">Tên ví:</label>
                                        <input type="text" name="ten" class="vTextField" maxlength="45" id="id_ten">
                                </div>
                        </div>
                        <div class="form-row field-dinh_muc">
                                <div>
                                        <label for="id_dinh_muc">Định mức:</label>
                                        <input type="number" name="dinh_muc" class="vIntegerField" id="id_dinh_muc">
                                </div>
                        </div>
                        <div class="form-row field-so_du">
                                <div>
                                        <label for="id_so_du">Số dư:</label>
                                        <input type="number" name="so_du" class="vIntegerField" id="id_so_du">
                                </div>
                        </div>
                </fieldset>
        </div>
        <div class="submit-row">
                <input type="submit" value="Save" class="default" name="_save">
        </div>
</form>
{% endblock %}

qlct_ca_nhan/templates/qlct_ca_nhan/themvi_thuchien.html
{% extends "qlct_ca_nhan/qlct_canhan.html" %}
{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom">
        <div class="w3-container w3-center w3-content" style="margin-top:155px; margin-bottom:150px; color:hsl(201, 18%, 37%);">
        <h1>Thêm ví thành công!</h1>
        </div>            
</div>
{% endblock %}